name: Build APP

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  buildApp:
    name: build and release app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: upload artifacts windows
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: ${{ matrix.os }}
          path: |
            release/**/History_*.exe

      - name: upload artifacts macos
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: ${{ matrix.os }}
          path: |
            release/**/History_*.dmg
